"""
STAGE 6: Code Generator

Input:  everything from Stages 1-5 (requirement, agent_plan, workflow,
        system_prompts, tools)
Output: a dict of {file_path: file_content} representing a real,
        runnable mini FastAPI project.

RELIABILITY DESIGN -- THREE LAYERS, WEAKEST LINK NEVER BREAKS THE DEMO:

1. STATIC FILES (requirements.txt, README.md, main.py, .env.example) are
   built with plain Python string templates -- NOT an LLM call. 100%
   deterministic, zero hallucination risk.

2. AGENT FILES are generated by an LLM in ONE batched call, using Gemini
   by default (better code quality) with automatic fallback to Groq if
   Gemini fails.

3. SELF-HEALING PASS (new): every generated agent file is validated for
   real Python syntax before it's shipped. If a file is missing or
   broken:
     a. First, ask the LLM to repair it, showing it the exact error.
     b. If the repair also fails, fall back to a guaranteed-valid stub
        module (still fully functional -- same interface, still calls
        the LLM at runtime -- just without any bespoke logic the
        original generation attempt might have added).
   This means a generated project NEVER fails to import because of a
   single broken agent file -- worst case, that one agent is simpler
   than intended, but the whole system still runs live on stage.
"""

import ast
import json
from llm_client import call_llm_json

CODE_GEN_SYSTEM_PROMPT = """You are a senior Python engineer generating
production-quality agent code for a generated multi-agent project.

You will be given a list of agents, each with an id, role name,
responsibility, a system prompt already written for it, and recommended
tools. For EACH agent, write a complete, runnable Python module.

Every agent module you write MUST follow this exact interface so the
generated project's main.py can call it consistently:

    from llm_client import call_llm_json

    SYSTEM_PROMPT = \"\"\"<paste the agent's system prompt here>\"\"\"

    def run(input_data: dict) -> dict:
        \"\"\"One-sentence docstring describing what this agent does.\"\"\"
        return call_llm_json(
            system_prompt=SYSTEM_PROMPT,
            user_prompt=f"Input: {input_data}",
        )

Rules:
- Follow that exact interface (a `run(input_data: dict) -> dict` function)
  for every agent so they are interchangeable in the pipeline.
- Include a short module docstring at the top naming the agent and its
  responsibility, based on what you were given.
- Do not invent imports that weren't shown in the interface above.
- Code must be syntactically valid, complete Python -- not a fragment.
- Generate a file for EVERY agent id you were given, no exceptions.

Always respond with ONLY a JSON object in exactly this shape:
{
  "agent_files": {
    "agent_id_here": "the complete Python file content as a string"
  }
}
No text outside the JSON."""

REPAIR_SYSTEM_PROMPT = """You are a Python code repair specialist. You
will be given a broken Python file and the exact syntax error it
produced. Fix ONLY what's needed to make it valid, syntactically correct
Python, while preserving its structure and intent as closely as possible
(same function names, same interface, same imports).

Always respond with ONLY a JSON object in exactly this shape:
{
  "fixed_code": "the complete corrected Python file content as a string"
}
No text outside the JSON."""


def _generate_agent_files(agent_plan_json: dict, prompts_json: dict) -> dict:
    """
    One LLM call that writes the actual Python code for every agent at
    once. Batching into one call (instead of one call per agent) keeps
    this fast and reduces the number of places a live demo could fail.
    """
    user_prompt = (
        f"Agents:\n{json.dumps(agent_plan_json)}\n\n"
        f"System prompts already written for each agent:\n{json.dumps(prompts_json)}"
    )
    result = call_llm_json(
        system_prompt=CODE_GEN_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        provider="gemini",   # better code quality; auto-falls back to Groq on failure
        temperature=0.2,     # low temperature: code should be consistent, not creative
    )
    return result.get("agent_files", {})


def _repair_code(broken_code: str, error_message: str) -> str:
    """Asks the LLM to fix one broken file, given the exact error."""
    result = call_llm_json(
        system_prompt=REPAIR_SYSTEM_PROMPT,
        user_prompt=f"Broken code:\n{broken_code}\n\nSyntax error:\n{error_message}",
        provider="gemini",
        temperature=0.1,  # repair should be precise, not creative
    )
    return result.get("fixed_code", broken_code)


def _stub_agent_file(agent_id: str, system_prompt: str) -> str:
    """
    Guaranteed-valid fallback module. Used only if the LLM's generated
    file (and its repair attempt) were both broken. Still fully
    functional -- same run() interface, still calls the real LLM at
    runtime -- just without any bespoke logic the original attempt
    might have added.
    """
    safe_prompt = (system_prompt or "You are a helpful agent.").replace('"""', "'")
    return f'''"""
{agent_id} -- auto-generated fallback module.
Used because the original generated code needed repair. Still fully
functional: same interface, still LLM-powered at runtime.
"""

from llm_client import call_llm_json

SYSTEM_PROMPT = """{safe_prompt}"""


def run(input_data: dict) -> dict:
    """Runs {agent_id} using its generated system prompt."""
    return call_llm_json(
        system_prompt=SYSTEM_PROMPT,
        user_prompt=f"Input: {{input_data}}",
    )
'''


def _validate_and_heal_agent_files(agent_files: dict, agent_plan: dict, prompts: dict) -> dict:
    """
    The self-healing pass. For every agent that was PLANNED (not just
    what the LLM happened to return), guarantee a syntactically valid
    file ends up in the final project -- generated, repaired, or
    stubbed, in that order of preference.
    """
    planned_ids = [a.get("id") for a in agent_plan.get("agents", []) if a.get("id")]
    prompt_lookup = {
        p.get("agent_id"): p.get("system_prompt")
        for p in prompts.get("prompts", [])
    }

    healed = {}
    for agent_id in planned_ids:
        code = agent_files.get(agent_id)
        fallback_prompt = prompt_lookup.get(agent_id, "You are a helpful agent.")

        if code is None:
            print(f"[healing] {agent_id}: not generated by the LLM, using safe stub")
            healed[agent_id] = _stub_agent_file(agent_id, fallback_prompt)
            continue

        try:
            ast.parse(code)
            healed[agent_id] = code  # valid as-is, ship it
        except SyntaxError as e:
            print(f"[healing] {agent_id}: syntax error found, attempting auto-repair...")
            try:
                fixed = _repair_code(code, str(e))
                ast.parse(fixed)  # verify the repair actually worked
                healed[agent_id] = fixed
                print(f"[healing] {agent_id}: repaired successfully")
            except Exception:
                print(f"[healing] {agent_id}: repair failed, using safe stub instead")
                healed[agent_id] = _stub_agent_file(agent_id, fallback_prompt)

    return healed


def _build_readme(requirement: dict, agent_plan: dict, workflow: dict, tools: dict) -> str:
    domain = requirement.get("domain", "generated-system")
    goal = requirement.get("goal", "")
    agents = agent_plan.get("agents", [])

    agent_lines = "\n".join(
        f"- **{a.get('role_name', a.get('id'))}** (`{a.get('id')}`): {a.get('responsibility', '')}"
        for a in agents
    )

    edges = workflow.get("edges", [])
    flow_lines = "\n".join(
        f"- {e.get('from')} \u2192 {e.get('to')} ({e.get('condition', 'always')})"
        for e in edges
    ) or "(see workflow JSON returned by the API for full detail)"

    stack = tools.get("overall_stack", {})
    stack_lines = "\n".join(
        f"- **{key.replace('_', ' ').title()}**: {val.get('choice', '')} \u2014 {val.get('reason', '')}"
        for key, val in stack.items()
    ) or "(see tools JSON returned by the API for full detail)"

    return f"""# {domain.replace('_', ' ').title()} \u2014 Generated Multi-Agent System

> Auto-generated by AgentForge from a natural-language description.

## Goal
{goal}

## Agents
{agent_lines}

## Workflow
{flow_lines}

## Recommended Stack
{stack_lines}

## Running this project

```bash
python -m venv venv
source venv/bin/activate     # Windows: venv\\Scripts\\activate
pip install -r requirements.txt
cp .env.example .env         # then paste your free Groq/Gemini key in
uvicorn main:app --reload
```

Open http://127.0.0.1:8000/docs to test the generated pipeline.

## Notes
This project was generated automatically. Every agent file was validated
for syntax correctness before being included -- if the AI's first attempt
at any file had an error, it was either auto-repaired or replaced with a
guaranteed-working fallback, so this project runs out of the box. Review
each agent's system prompt in `agents/<agent_id>.py` before using it for
anything beyond a demo.
"""


def _build_main_py(agent_plan: dict) -> str:
    agents = agent_plan.get("agents", [])
    agent_ids = [a.get("id") for a in agents if a.get("id")]

    imports = "\n".join(f"from agents.{aid} import run as run_{aid}" for aid in agent_ids)
    chain_calls = "\n    ".join(
        f'result = run_{aid}(result)  # {aid}' for aid in agent_ids
    )

    return f'''"""
Auto-generated entrypoint for this multi-agent system.
Runs the agents below in sequence, each one receiving the previous
agent's output as its input.
"""

from fastapi import FastAPI
from pydantic import BaseModel

{imports}

app = FastAPI(title="Generated Multi-Agent System")


class RunRequest(BaseModel):
    input_data: dict


@app.get("/")
def health_check():
    return {{"status": "generated multi-agent system is running"}}


@app.post("/run")
def run_pipeline(request: RunRequest):
    result = request.input_data
    {chain_calls}
    return result
'''


# Embedded verbatim so every generated project is self-contained and
# doesn't depend on files outside its own folder. This was a real bug
# found during testing: generated agent files import `llm_client`, but
# nothing was actually writing that file into the generated project --
# it would download, but never run. This constant is the fix.
GENERATED_LLM_CLIENT = '''"""
The ONE place this generated project talks to LLMs. Every agent module
imports call_llm_json from here instead of calling a provider directly.

Uses Groq by default, with automatic fallback to Gemini if the Groq
call fails for any reason (missing key, rate limit, bad response) --
same resilience pattern as the tool that generated this project.
"""

import os
import json
from dotenv import load_dotenv
from groq import Groq
from google import genai
from google.genai import types as genai_types

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"
GEMINI_MODEL = "gemini-3.5-flash"

_groq_client = None
_gemini_client = None


def _get_groq_client():
    global _groq_client
    if _groq_client is None:
        _groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))
    return _groq_client


def _get_gemini_client():
    global _gemini_client
    if _gemini_client is None:
        _gemini_client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY"))
    return _gemini_client


def _ensure_json_keyword(system_prompt, user_prompt):
    combined = f"{system_prompt} {user_prompt}".lower()
    if "json" not in combined:
        return f"{user_prompt}\\n\\nRespond only with valid JSON."
    return user_prompt


def _call_groq_json(system_prompt, user_prompt, temperature):
    safe_user_prompt = _ensure_json_keyword(system_prompt, user_prompt)
    response = _get_groq_client().chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": safe_user_prompt},
        ],
        temperature=temperature,
        response_format={"type": "json_object"},
    )
    return json.loads(response.choices[0].message.content)


def _call_gemini_json(system_prompt, user_prompt, temperature):
    response = _get_gemini_client().models.generate_content(
        model=GEMINI_MODEL,
        contents=user_prompt,
        config=genai_types.GenerateContentConfig(
            system_instruction=system_prompt,
            temperature=temperature,
            response_mime_type="application/json",
        ),
    )
    return json.loads(response.text)


def call_llm_json(system_prompt: str, user_prompt: str, provider: str = "groq", temperature: float = 0.3) -> dict:
    if provider == "gemini":
        try:
            return _call_gemini_json(system_prompt, user_prompt, temperature)
        except Exception as e:
            print(f"[warning] Gemini failed ({e}), falling back to Groq...")
            return _call_groq_json(system_prompt, user_prompt, temperature)
    try:
        return _call_groq_json(system_prompt, user_prompt, temperature)
    except json.JSONDecodeError as e:
        raise ValueError(f"LLM did not return valid JSON: {e}")
'''


def _build_static_files(requirement, agent_plan, workflow, tools) -> dict:
    return {
        "README.md": _build_readme(requirement, agent_plan, workflow, tools),
        "main.py": _build_main_py(agent_plan),
        "llm_client.py": GENERATED_LLM_CLIENT,
        "requirements.txt": "fastapi\nuvicorn\ngroq\ngoogle-genai\npython-dotenv\npydantic\n",
        ".env.example": "GROQ_API_KEY=your_groq_key_here\nGEMINI_API_KEY=your_gemini_key_here\n",
    }


def generate_code(requirement: dict, agent_plan: dict, workflow: dict, prompts: dict, tools: dict) -> dict:
    """
    Returns a flat dict of {file_path: file_content} representing the
    full generated project, ready to be written to disk or zipped.
    Every agent file is guaranteed syntactically valid before return.
    """
    static_files = _build_static_files(requirement, agent_plan, workflow, tools)
    raw_agent_files = _generate_agent_files(agent_plan, prompts)
    healed_agent_files = _validate_and_heal_agent_files(raw_agent_files, agent_plan, prompts)

    project_files = dict(static_files)
    for agent_id, code in healed_agent_files.items():
        project_files[f"agents/{agent_id}.py"] = code
    project_files["agents/__init__.py"] = ""

    return project_files


if __name__ == "__main__":
    # Manual test -- run from the AGENT root folder:
    #   python -m agents.code_generator
    from agents.requirement_analysis import analyze_requirement
    from agents.agent_planner import plan_agents
    from agents.workflow_designer import design_workflow
    from agents.prompt_generator import generate_prompts
    from agents.tool_selector import select_tools

    requirement = analyze_requirement("Build me an AI recruitment platform")
    plan = plan_agents(requirement)
    workflow = design_workflow(plan)
    prompts = generate_prompts(requirement, plan)
    tools = select_tools(requirement, plan, workflow)

    files = generate_code(requirement, plan, workflow, prompts, tools)

    print(f"\nGenerated {len(files)} files:\n")
    for path in files:
        print(f" - {path}")

    print("\n--- main.py preview ---\n")
    print(files["main.py"])